"""The title's achievement declaration: reader, validator and code generator.

One description of the set feeds the engine and every platform's packaging. This
module owns reading and checking it; platform packaging imports it rather than
parsing the declaration itself, so the two cannot disagree about what the set is.

    python3 tools/achievements.py --declaration game/config/achievements.json \
        --emit-ids build/generated/AchievementIds.h \
        --emit-table build/generated/AchievementTable.cpp

See docs/subsystems/ACHIEVEMENT.md.
"""

import argparse
import json
import os
import sys

ACHV_MAX_ENTRIES = 128

GRADES = ("platinum", "gold", "silver", "bronze")

DEFAULT_DECLARATION = os.path.join("game", "config", "achievements.json")


class AchievementError(Exception):
    """A declaration that cannot be built from, with the reason a person needs."""

    def __init__(self, where, message):
        super().__init__("{}: {}".format(where, message))


def load(path):
    """Read and validate the declaration. Raises AchievementError."""
    where = os.path.basename(path)
    try:
        with open(path, "r", encoding="utf-8") as handle:
            declaration = json.load(handle)
    except OSError as error:
        raise AchievementError(where, "cannot be read: {}".format(error))
    except ValueError as error:
        raise AchievementError(where, "is not valid JSON: {}".format(error))

    entries = declaration.get("achievements")
    if not isinstance(entries, list) or not entries:
        raise AchievementError(where, "declares no achievements")

    validate(entries, os.path.dirname(os.path.abspath(path)), where)
    return sorted(entries, key=lambda entry: entry["id"])


def validate(entries, declaration_dir, where):
    """Every check here stands for a failure that is silent until it is not."""
    if len(entries) > ACHV_MAX_ENTRIES:
        raise AchievementError(
            where, "{} achievements declared, the maximum is {}".format(len(entries), ACHV_MAX_ENTRIES))

    ids = [entry.get("id") for entry in entries]
    if any(not isinstance(value, int) for value in ids):
        raise AchievementError(where, "every achievement needs an integer id")
    if len(set(ids)) != len(ids):
        duplicates = sorted({value for value in ids if ids.count(value) > 1})
        raise AchievementError(where, "duplicate ids: {}".format(duplicates))
    if sorted(ids) != list(range(len(ids))):
        raise AchievementError(
            where,
            "ids must be dense and start at zero; got {}. A gap is an identifier with no entry "
            "behind it, which nothing at runtime can recover from.".format(sorted(ids)))

    keys = [entry.get("key") for entry in entries]
    if len(set(keys)) != len(keys):
        duplicates = sorted({key for key in keys if keys.count(key) > 1})
        raise AchievementError(where, "duplicate keys: {}".format(duplicates))

    platinums = [entry for entry in entries if entry.get("grade") == "platinum"]
    if len(platinums) > 1:
        raise AchievementError(
            where, "{} platinum achievements declared, at most one is allowed".format(len(platinums)))

    for entry in entries:
        identifier = entry.get("id")
        if entry.get("grade") not in GRADES:
            raise AchievementError(
                where, "achievement {} has grade '{}', must be one of {}".format(
                    identifier, entry.get("grade"), list(GRADES)))
        if not entry.get("key"):
            raise AchievementError(where, "achievement {} has no key".format(identifier))
        if not entry.get("name"):
            raise AchievementError(where, "achievement {} has no name".format(identifier))
        icon = entry.get("icon")
        if icon and not os.path.exists(os.path.join(declaration_dir, icon)):
            raise AchievementError(
                where, "achievement {} icon points at a missing file: {}".format(identifier, icon))


def platinum_id(entries):
    """@return The platinum's identifier, or None where the set has no platinum."""
    for entry in entries:
        if entry["grade"] == "platinum":
            return entry["id"]
    return None


def _escape(text):
    return str(text).replace("\\", "\\\\").replace('"', '\\"')


def emit_ids(entries, out_path):
    """The enumerator a game names an achievement by."""
    lines = [
        "#pragma once",
        "",
        "// Generated by tools/achievements.py from the title's achievement declaration.",
        "// Do not edit: regenerate by building.",
        "",
        "#include <cstdint>",
        "",
        "/// An achievement this title declares. Values are fixed for the life of the",
        "/// title: changing one reassigns what a player has already earned.",
        "enum class AchievementId : uint8_t",
        "{",
    ]
    for entry in entries:
        detail = entry.get("detail", "")
        comment = " // {}".format(entry["grade"]) + (" - {}".format(detail) if detail else "")
        lines.append("    {} = {},{}".format(entry["key"], entry["id"], comment))
    lines += ["", "    Count = {}".format(len(entries)), "};", ""]
    _write(out_path, "\n".join(lines))
    return out_path


def emit_table(entries, out_path):
    """What the engine needs to show an unlock: the strings and the grade."""
    lines = [
        "// Generated by tools/achievements.py from the title's achievement declaration.",
        "// Do not edit: regenerate by building.",
        "",
        '#include "EngineAchievement.h"',
        "",
        "namespace",
        "{",
        "    struct AchievementRecord",
        "    {",
        "        const char* name;",
        "        const char* detail;",
        "        AchievementGrade grade;",
        "        bool hidden;",
        "    };",
        "",
        "    const AchievementRecord kAchievements[] =",
        "    {",
    ]
    for entry in entries:
        lines.append('        {{ "{}", "{}", AchievementGrade::{}, {} }},'.format(
            _escape(entry["name"]),
            _escape(entry.get("detail", "")),
            entry["grade"].capitalize(),
            "true" if entry.get("hidden") else "false"))
    lines += [
        "    };",
        "",
        "    const uint32_t kAchievementCount = {};".format(len(entries)),
        "}",
        "",
        "uint32_t Engine_Achievement_DeclaredCount() { return kAchievementCount; }",
        "",
        "const char* Engine_Achievement_GetName(uint32_t id)",
        "{",
        "    return (id < kAchievementCount) ? kAchievements[id].name : \"\";",
        "}",
        "",
        "const char* Engine_Achievement_GetDetail(uint32_t id)",
        "{",
        "    return (id < kAchievementCount) ? kAchievements[id].detail : \"\";",
        "}",
        "",
        "AchievementGrade Engine_Achievement_GetGrade(uint32_t id)",
        "{",
        "    return (id < kAchievementCount) ? kAchievements[id].grade : AchievementGrade::Bronze;",
        "}",
        "",
        "bool Engine_Achievement_IsHidden(uint32_t id)",
        "{",
        "    return (id < kAchievementCount) && kAchievements[id].hidden;",
        "}",
        "",
    ]
    _write(out_path, "\n".join(lines))
    return out_path


def _write(path, text):
    parent = os.path.dirname(os.path.abspath(path))
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def main(argv=None):
    parser = argparse.ArgumentParser(description="Achievement declaration reader and generator")
    parser.add_argument("--declaration", default=DEFAULT_DECLARATION)
    parser.add_argument("--emit-ids")
    parser.add_argument("--emit-table")
    args = parser.parse_args(argv)

    try:
        entries = load(args.declaration)
    except AchievementError as error:
        print("achievements: {}".format(error), file=sys.stderr)
        return 1

    if args.emit_ids:
        print("achievement ids ->", emit_ids(entries, args.emit_ids))
    if args.emit_table:
        print("achievement table ->", emit_table(entries, args.emit_table))

    print("achievements: OK - {} declared".format(len(entries)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
