#!/usr/bin/env python3
"""Vita shader compiler wrapper.

Compiles one Cg shader to the console's shader format and emits it as a C header
holding the bytes, so the blob is linked into the executable and the title never
compiles a shader at run time.

Why a wrapper rather than calling the compiler from CMake directly: the compiler
is a WINDOWS executable, and this project builds under WSL. It runs fine there
through interop, but it is a Windows process and only understands Windows path
strings - handed a Linux path it fails with "the target path is invalid", which
says nothing about the real cause. All of that translation lives here so the
build rule stays one line.

The compiler is NOT in this repository and is not committed. See docs/vita/BUILD.md.

Usage:
    python3 tools/compile_shader.py --profile vertex \\
        --input  engine/platform/vita/renderer/shaders/scene_v.cg \\
        --output build/generated/vita/scene_v.h \\
        --symbol scene_v_gxp
"""

import argparse
import os
import shutil
import subprocess
import sys

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_COMPILER = os.path.join(PROJECT_ROOT, "external", "psp2cgc", "psp2cgc.exe")

PROFILES = {"vertex": "sce_vp_psp2", "fragment": "sce_fp_psp2"}


class ShaderError(Exception):
    pass


def find_compiler(explicit):
    """Explicit path, then the environment, then the vendored location."""
    if explicit:
        if os.path.exists(explicit):
            return os.path.abspath(explicit)
        raise ShaderError(f"--compiler '{explicit}' does not exist")

    for candidate in (os.environ.get("PSP2CGC"), DEFAULT_COMPILER):
        if candidate and os.path.exists(candidate):
            return os.path.abspath(candidate)
    raise ShaderError(
        "psp2cgc not found.\n"
        f"  Looked at: {explicit or '(no --compiler)'}, $PSP2CGC, {DEFAULT_COMPILER}\n"
        "  The Vita graphics backends need it to compile shaders at build time.\n"
        "  It is deliberately not committed to this repository; see docs/vita/BUILD.md.")


def host_path(path):
    """Translate a path into the form the compiler process will understand.

    Under WSL the compiler is a Windows process, so every path it is handed -
    input, output, include directories - has to be converted. Everywhere else the
    path is already in the right form.
    """
    path = os.path.abspath(path)
    if sys.platform == "win32" or not shutil.which("wslpath"):
        return path
    try:
        return subprocess.check_output(["wslpath", "-w", path], text=True).strip()
    except subprocess.CalledProcessError:
        return path


def missing_parameters(blob, required):
    """Report which required parameters the compiler did not keep.

    An unused attribute is optimised away, and the name then cannot be found at
    run time - which fails renderer setup on hardware rather than at build time.

    @param blob The compiled shader binary.
    @param required Parameter names the backend binds.
    @return The names that are absent, in the order given.
    """
    return [name for name in required if b"\0" + name.encode("ascii") + b"\0" not in blob]


def compile_shader(compiler, profile, input_path, gxp_path):
    if profile not in PROFILES:
        raise ShaderError(f"unknown profile '{profile}', expected one of {sorted(PROFILES)}")

    os.makedirs(os.path.dirname(os.path.abspath(gxp_path)) or ".", exist_ok=True)

    cmd = [compiler, "-profile", PROFILES[profile], host_path(input_path), "-o", host_path(gxp_path)]

    proc = subprocess.run(cmd, capture_output=True, text=True)
    output = (proc.stdout or "") + (proc.stderr or "")

    if proc.returncode != 0 or not os.path.exists(gxp_path):
        raise ShaderError(f"compiling {input_path} failed:\n{output.strip() or '(no output)'}")

    with open(gxp_path, "rb") as fh:
        blob = fh.read()
    if blob[:4] != b"GXP\0":
        raise ShaderError(f"{gxp_path} is not a shader binary (magic {blob[:4]!r})")
    return blob, output.strip()


def write_header(blob, symbol, out_path, source_name):
    lines = [
        "#pragma once",
        "",
        f"// Generated by tools/compile_shader.py from {source_name}.",
        "// Do not edit: regenerate by building.",
        "",
        "#include <cstdint>",
        "",
        f"// {len(blob)} bytes of compiled shader, linked into the executable so the",
        "// title never needs a shader compiler on the console.",
        f"static const uint8_t {symbol}[] = {{",
    ]
    for i in range(0, len(blob), 12):
        chunk = ", ".join(f"0x{b:02X}" for b in blob[i:i + 12])
        lines.append(f"    {chunk},")
    lines += ["};", "", f"static const uint32_t {symbol}_size = {len(blob)}u;", ""]

    os.makedirs(os.path.dirname(os.path.abspath(out_path)) or ".", exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))


def main(argv=None):
    ap = argparse.ArgumentParser(description="Compile a Vita Cg shader into a linkable header")
    ap.add_argument("--compiler", help="path to psp2cgc (default: $PSP2CGC, then external/psp2cgc/)")
    ap.add_argument("--profile", required=True, choices=sorted(PROFILES))
    ap.add_argument("--input", required=True)
    ap.add_argument("--output", required=True, help="the C header to write")
    ap.add_argument("--symbol", help="C identifier for the blob (default: from the input name)")
    ap.add_argument("--keep-gxp", help="also keep the raw shader binary at this path")
    ap.add_argument("--require", action="append", default=[], metavar="NAME",
                    help="fail unless the compiled shader still exposes this parameter (repeatable)")
    args = ap.parse_args(argv)

    try:
        compiler = find_compiler(args.compiler)
        symbol = args.symbol or (os.path.splitext(os.path.basename(args.input))[0] + "_gxp")
        gxp = args.keep_gxp or (os.path.splitext(args.output)[0] + ".gxp")

        blob, log = compile_shader(compiler, args.profile, args.input, gxp)

        absent = missing_parameters(blob, args.require)
        if absent:
            raise ShaderError(
                "%s compiled, but these parameters were optimised away: %s\n"
                "  The renderer binds them by name, so it would fail to start on hardware.\n"
                "  Either use them in the shader, or stop binding them."
                % (os.path.basename(args.input), ", ".join(absent)))

        write_header(blob, symbol, args.output, os.path.basename(args.input))
        if log:
            print(log)
        print(f"shader: {os.path.basename(args.input)} -> {args.output} ({len(blob)} bytes)")
    except ShaderError as exc:
        print(f"compile_shader: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
