#!/usr/bin/env python3
"""Theme declaration reader and generator.

game/theme.json is the single source of truth for the interface's look. The
themes it declares are compiled into the binary, because the interface must be
able to draw before any filesystem exists and because a built-in theme is what a
refused load falls back to. The same declaration also cooks to loadable theme
assets.

    python3 tools/theme.py --emit-ids   build/generated/theme/UiThemeIds.h
    python3 tools/theme.py --emit-table build/generated/theme/UiThemeTable.cpp
"""

import argparse
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ps2lib import theme as themelib

DEFAULT_DECLARATION = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "game", "theme.json")
ENGINE_UI_HEADER = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "engine", "include", "EngineUi.h")


class ThemeDeclarationError(ValueError):
    """A declaration that cannot produce a theme, with the reason."""


def engine_color_roles(header_path=ENGINE_UI_HEADER):
    """Read the colour roles out of the engine's own enum.

    The declaration is checked against this rather than against a second copy of
    the list, so a role added to the engine and forgotten in the theme fails the
    build instead of producing a theme with a missing colour.
    """
    with open(header_path, "r", encoding="utf-8") as fh:
        text = fh.read()
    m = re.search(r"enum class UiColor\s*:\s*\w+\s*\{(.*?)\}", text, re.S)
    if not m:
        raise ThemeDeclarationError("could not find enum class UiColor in EngineUi.h")

    roles = []
    for line in m.group(1).splitlines():
        line = line.split("//")[0].strip().rstrip(",")
        if not line:
            continue
        name = line.split("=")[0].strip()
        if not name or name == "Count":
            continue
        roles.append(name)
    return roles


ALL_METRIC_NAMES = frozenset(themelib.INT_METRICS) | {"repeatDelaySeconds", "repeatIntervalSeconds"}


def theme_metrics(decl, entry):
    """A theme's metrics: the declaration's defaults, with anything the theme
    itself names overridden field by field.

    A theme is a style -- colours *and* metrics -- so `CONTRAST`, sized for a
    small or poor display, can ask for a larger textScale without every other
    theme paying for it too.
    """
    merged = dict(decl.get("metrics") or {})
    merged.update(entry.get("metrics") or {})
    return merged


def load(path):
    with open(path, "r", encoding="utf-8-sig") as fh:
        decl = json.load(fh)

    themes = decl.get("themes") or []
    if not themes:
        raise ThemeDeclarationError("no themes declared")

    defaults = decl.get("metrics") or {}
    themelib._check_metrics(defaults)

    roles = engine_color_roles()
    seen = set()
    for entry in themes:
        name = entry.get("name")
        if not name or not re.fullmatch(r"[A-Z][A-Z0-9_]*", name):
            raise ThemeDeclarationError(f"theme name {name!r} must be upper snake case")
        if name in seen:
            raise ThemeDeclarationError(f"duplicate theme name {name!r}")
        seen.add(name)

        colors = entry.get("colors") or {}
        missing = [r for r in roles if r not in colors]
        if missing:
            raise ThemeDeclarationError(f"theme {name}: no colour for {', '.join(missing)}")
        extra = [r for r in colors if r not in roles]
        if extra:
            raise ThemeDeclarationError(f"theme {name}: {', '.join(extra)} name no colour role")

        override = entry.get("metrics") or {}
        unknown = [k for k in override if k not in ALL_METRIC_NAMES]
        if unknown:
            raise ThemeDeclarationError(f"theme {name}: metrics override names unknown metric(s) {', '.join(unknown)}")
        try:
            themelib._check_metrics(theme_metrics(decl, entry))
        except themelib.ThemeError as e:
            raise ThemeDeclarationError(f"theme {name}: {e}")

    for role in (decl.get("fonts") or {}):
        if role not in themelib.FONT_ROLES:
            raise ThemeDeclarationError(f"unknown font role {role!r}")

    return decl


def _write(path, text):
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)


def emit_ids(decl, out_path):
    """The enumerator a caller names a built-in theme by."""
    lines = [
        "#pragma once",
        "",
        "// Generated by tools/theme.py from the title's theme declaration.",
        "// Do not edit: regenerate by building.",
        "",
        "#include <cstdint>",
        "",
        "/// A theme compiled into the binary. Always available, because the",
        "/// interface must be able to draw before a filesystem exists.",
        "enum class UiBuiltinTheme : uint8_t",
        "{",
    ]
    for i, entry in enumerate(decl["themes"]):
        detail = entry.get("description", "")
        lines.append("    {} = {},{}".format(entry["name"], i, (" // " + detail) if detail else ""))
    lines += ["", "    Count = {}".format(len(decl["themes"])), "};", ""]
    _write(out_path, "\n".join(lines))
    return out_path


def emit_table(decl, out_path):
    """The colour tables and metrics for every theme, colours and metrics both
    per theme rather than shared, so a theme is a whole style."""
    roles = engine_color_roles()
    fonts = decl.get("fonts") or {}

    lines = [
        "// Generated by tools/theme.py from the title's theme declaration.",
        "// Do not edit: regenerate by building.",
        "",
        '#include "EngineUi.h"',
        "",
        "namespace",
        "{",
        "    UiRgba Rgba(uint8_t r, uint8_t g, uint8_t b, uint8_t a)",
        "    {",
        "        UiRgba c;",
        "        c.r = r;",
        "        c.g = g;",
        "        c.b = b;",
        "        c.a = a;",
        "        return c;",
        "    }",
        "} // namespace",
        "",
        "const char* Ui_BuiltinThemeName(UiBuiltinTheme theme)",
        "{",
        "    switch (theme)",
        "    {",
    ]
    for entry in decl["themes"]:
        lines.append('    case UiBuiltinTheme::{}:'.format(entry["name"]))
        lines.append('        return "{}";'.format(entry["name"]))
    lines += [
        "    case UiBuiltinTheme::Count:",
        "        break;",
        "    }",
        '    return "?";',
        "}",
        "",
        "UiStyle Ui_BuiltinTheme(UiBuiltinTheme theme)",
        "{",
        "    UiStyle s;",
        "    for (uint8_t i = 0; i < static_cast<uint8_t>(UiColor::Count); ++i)",
        "        s.colors[i] = Rgba(0, 0, 0, 255);",
        "",
    ]
    lines.append("    s.reserved[0] = 0;")
    lines += ["", "    switch (theme)", "    {"]

    for entry in decl["themes"]:
        entry_metrics = theme_metrics(decl, entry)
        lines.append("    case UiBuiltinTheme::{}:".format(entry["name"]))
        for role in roles:
            r, g, b, a = entry["colors"][role]
            lines.append("        s.colors[static_cast<uint8_t>(UiColor::{})] = Rgba({}, {}, {}, {});".format(role, r, g, b, a))
        for name in themelib.INT_METRICS:
            lines.append("        s.{} = {};".format(name, entry_metrics[name]))
        lines.append("        s.repeatDelaySeconds = {}f;".format(entry_metrics["repeatDelaySeconds"]))
        lines.append("        s.repeatIntervalSeconds = {}f;".format(entry_metrics["repeatIntervalSeconds"]))
        lines.append("        break;")
    lines += [
        "    case UiBuiltinTheme::Count:",
        "        break;",
        "    }",
        "    return s;",
        "}",
        "",
        "const char* Ui_BuiltinRoleFont(UiFontRole role)",
        "{",
        "    switch (role)",
        "    {",
    ]
    for role in themelib.FONT_ROLES:
        lines.append("    case UiFontRole::{}:".format(role))
        lines.append('        return "{}";'.format(fonts.get(role, "")))
    lines += [
        "    case UiFontRole::Count:",
        "        break;",
        "    }",
        '    return "";',
        "}",
        "",
    ]
    _write(out_path, "\n".join(lines))
    return out_path


def cook_payloads(decl):
    """Every declared theme as a cooked payload, keyed by asset name."""
    out = {}
    for entry in decl["themes"]:
        blob, _ = themelib.write_theme(entry["colors"], theme_metrics(decl, entry), decl.get("fonts"))
        out["THEME_" + entry["name"]] = blob
    return out


def main(argv=None):
    parser = argparse.ArgumentParser(description="Theme declaration reader and generator")
    parser.add_argument("--declaration", default=DEFAULT_DECLARATION)
    parser.add_argument("--emit-ids")
    parser.add_argument("--emit-table")
    args = parser.parse_args(argv)

    try:
        decl = load(args.declaration)
    except (ThemeDeclarationError, themelib.ThemeError, OSError, ValueError) as e:
        print(f"theme: {e}", file=sys.stderr)
        return 1

    if args.emit_ids:
        print("theme: wrote", emit_ids(decl, args.emit_ids))
    if args.emit_table:
        print("theme: wrote", emit_table(decl, args.emit_table))
    if not args.emit_ids and not args.emit_table:
        print(f"theme: {len(decl['themes'])} theme(s) declared, all valid")
    return 0


if __name__ == "__main__":
    sys.exit(main())
