"""The title's identity: reader and validator.

Who made the title, what it is called, and what each platform calls it. Platform
packaging and the engine's writable-storage location are both built from this, so
the identity a console shows and the identity a save is filed under cannot
disagree.

    python3 tools/title.py --declaration game/config/title.json

See docs/subsystems/ACHIEVEMENT.md and each platform's spec.
"""

import argparse
import json
import os
import re
import sys

DEFAULT_DECLARATION = os.path.join("game", "config", "title.json")

ID_PATTERN = re.compile(r"^[A-Z]{4}[0-9]{5}$")
VERSION_PATTERN = re.compile(r"^[0-9][0-9]\.[0-9][0-9]$")
PATH_UNSAFE = set('\\/:*?"<>|')


class TitleError(Exception):
    """A declaration that cannot be built from, with the reason a person needs."""

    def __init__(self, where, message):
        super().__init__("{}: {}".format(where, message))


def load(path=DEFAULT_DECLARATION):
    """Read and validate the title declaration. Raises TitleError."""
    where = os.path.basename(path)
    try:
        with open(path, "r", encoding="utf-8") as handle:
            declaration = json.load(handle)
    except OSError as error:
        raise TitleError(where, "cannot be read: {}".format(error))
    except ValueError as error:
        raise TitleError(where, "is not valid JSON: {}".format(error))

    validate(declaration, where)
    return declaration


def validate(declaration, where):
    for field in ("developer", "name"):
        value = declaration.get(field)
        if not isinstance(value, str) or not value:
            raise TitleError(where, "{} is required and must not be empty".format(field))
        if PATH_UNSAFE & set(value):
            raise TitleError(
                where,
                "{} '{}' carries a character a directory name cannot; it names a folder on at least "
                "one platform".format(field, value))

    version = declaration.get("version", "")
    if not VERSION_PATTERN.match(version):
        raise TitleError(where, "version '{}' must be ##.##".format(version))

    ids = declaration.get("ids")
    if not isinstance(ids, dict):
        raise TitleError(where, "ids is required")
    for platform, value in ids.items():
        if not ID_PATTERN.match(value or ""):
            raise TitleError(
                where,
                "ids.{} '{}' must be four upper-case letters then five digits".format(platform, value))
    return declaration


def platform_id(declaration, platform, where=DEFAULT_DECLARATION):
    """@return The identifier this platform files saves and packages under.
    @raise TitleError When the platform needs one and none was declared."""
    value = (declaration.get("ids") or {}).get(platform)
    if not value:
        raise TitleError(os.path.basename(where), "ids.{} is required to build for {}".format(platform, platform))
    return value


def emit_header(declaration, out_path):
    """The identity a platform builds its writable-storage location from."""
    ids = declaration.get("ids") or {}
    lines = [
        "#pragma once",
        "",
        "// Generated by tools/title.py from the title declaration.",
        "// Do not edit: regenerate by building.",
        "",
        '#define TITLE_DEVELOPER "{}"'.format(_escape(declaration["developer"])),
        '#define TITLE_NAME "{}"'.format(_escape(declaration["name"])),
        '#define TITLE_VERSION "{}"'.format(_escape(declaration["version"])),
    ]
    for platform in sorted(ids):
        lines.append('#define TITLE_ID_{} "{}"'.format(platform.upper(), _escape(ids[platform])))
    lines.append("")

    parent = os.path.dirname(os.path.abspath(out_path))
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    return out_path


def _escape(text):
    return str(text).replace("\\", "\\\\").replace('"', '\\"')


def main(argv=None):
    parser = argparse.ArgumentParser(description="Title identity reader and validator")
    parser.add_argument("--declaration", default=DEFAULT_DECLARATION)
    parser.add_argument("--emit-header")
    args = parser.parse_args(argv)

    try:
        declaration = load(args.declaration)
    except TitleError as error:
        print("title: {}".format(error), file=sys.stderr)
        return 1

    if args.emit_header:
        print("title header ->", emit_header(declaration, args.emit_header))

    print("title: OK - '{}' by '{}' version {}, ids {}".format(
        declaration["name"], declaration["developer"], declaration["version"],
        ", ".join("{}={}".format(k, v) for k, v in sorted((declaration.get("ids") or {}).items()))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
