name: Lint and Security Checks

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  check-style:
    name: Clang-Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run clang-format
        uses: jidicula/clang-format-action@v4.14.0
        with:
          clang-format-version: '18'
          check-path: '.'
          fallback-style: 'none'

  analyze-codeql:
    name: CodeQL Security Scan
    needs: check-style
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: 'c-cpp'

      - name: Build Project via Script
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:c-cpp"